### ISSUE TITLE
Request for code for Lorenz63 plot in paper

### ISSUE THREAD

**Issue by rj678** [Team-RADDISH/ParticleDA.jl#250]
Hello - thank you for releasing this super helpful repo! 

I'd like to replicate Figure 3 (Lorenz63) of the paper - it'd help me greatly if you could point me to the code used to create the 3D plot for the Mean of the particles please 

thank you!

**Comment by matt-graham** [comment]
Hi @rj678. Apologies for the delay getting back to you on this. I've added a Lorenz 63 example Plut notebook as part of #251 (https://github.com/Team-RADDISH/ParticleDA.jl/blob/7ea9aba4d8f87f721de87821ab4b08bd803f71a1/extra/lorenz63_example.jl)  which shows how to create a plot comparable to those in the paper.

**Comment by rj678** [comment]
amazing! thank you so much!
