### ISSUE TITLE
Rename default branch to `main` 

### ISSUE THREAD

**Issue by matt-graham** [Team-RADDISH/ParticleDA.jl#265]
Looking for `master` references in code as well as updating README we'd need to update Actions workflows. 

We also have lots of usages of `master_rank` which I guess it may make sense to also update to `main_rank` or similar (though technically this would be a breaking change as we expose `master_rank` as a filter parameter). 

See also discussion in  https://github.com/Team-RADDISH/ParticleDA.jl/pull/264#discussion_r1523125063

**Comment by giordano** [comment]
I renamed the default branch of the repository to `main`.  For reference, people who cloned this repo in the past may want to run the commands
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
